// Mocks generated by Mockito 5.4.4 from annotations
// in interview_pro_app/test/features/interview/interview_question_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:interview_pro_app/shared/domain/entities/interview_question.dart'
    as _i2;
import 'package:interview_pro_app/shared/domain/entities/question_category.dart'
    as _i3;
import 'package:interview_pro_app/shared/domain/repositories/interview_question_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInterviewQuestion_0 extends _i1.SmartFake
    implements _i2.InterviewQuestion {
  _FakeInterviewQuestion_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestionCategoryEntity_1 extends _i1.SmartFake
    implements _i3.QuestionCategoryEntity {
  _FakeQuestionCategoryEntity_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [InterviewQuestionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInterviewQuestionRepository extends _i1.Mock
    implements _i4.InterviewQuestionRepository {
  MockInterviewQuestionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> hasQuestions() => (super.noSuchMethod(
        Invocation.method(
          #hasQuestions,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> hasCategories() => (super.noSuchMethod(
        Invocation.method(
          #hasCategories,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<List<_i2.InterviewQuestion>> getQuestions({
    String? category,
    String? difficulty,
    String? roleSpecific,
    List<String>? tags,
    int limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestions,
          [],
          {
            #category: category,
            #difficulty: difficulty,
            #roleSpecific: roleSpecific,
            #tags: tags,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i2.InterviewQuestion>>.value(
            <_i2.InterviewQuestion>[]),
      ) as _i5.Future<List<_i2.InterviewQuestion>>);

  @override
  _i5.Future<List<_i2.InterviewQuestion>> getQuestionsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByCategory,
          [category],
        ),
        returnValue: _i5.Future<List<_i2.InterviewQuestion>>.value(
            <_i2.InterviewQuestion>[]),
      ) as _i5.Future<List<_i2.InterviewQuestion>>);

  @override
  _i5.Future<List<_i2.InterviewQuestion>> getQuestionsByDifficulty(
          String? difficulty) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByDifficulty,
          [difficulty],
        ),
        returnValue: _i5.Future<List<_i2.InterviewQuestion>>.value(
            <_i2.InterviewQuestion>[]),
      ) as _i5.Future<List<_i2.InterviewQuestion>>);

  @override
  _i5.Future<List<_i2.InterviewQuestion>> getQuestionsByRole(String? role) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuestionsByRole,
          [role],
        ),
        returnValue: _i5.Future<List<_i2.InterviewQuestion>>.value(
            <_i2.InterviewQuestion>[]),
      ) as _i5.Future<List<_i2.InterviewQuestion>>);

  @override
  _i5.Future<List<_i2.InterviewQuestion>> getRandomQuestions({
    required int count,
    String? category,
    String? difficulty,
    String? roleSpecific,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomQuestions,
          [],
          {
            #count: count,
            #category: category,
            #difficulty: difficulty,
            #roleSpecific: roleSpecific,
          },
        ),
        returnValue: _i5.Future<List<_i2.InterviewQuestion>>.value(
            <_i2.InterviewQuestion>[]),
      ) as _i5.Future<List<_i2.InterviewQuestion>>);

  @override
  _i5.Future<_i2.InterviewQuestion> createQuestion(
          _i2.InterviewQuestion? question) =>
      (super.noSuchMethod(
        Invocation.method(
          #createQuestion,
          [question],
        ),
        returnValue:
            _i5.Future<_i2.InterviewQuestion>.value(_FakeInterviewQuestion_0(
          this,
          Invocation.method(
            #createQuestion,
            [question],
          ),
        )),
      ) as _i5.Future<_i2.InterviewQuestion>);

  @override
  _i5.Future<_i2.InterviewQuestion> updateQuestion(
          _i2.InterviewQuestion? question) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuestion,
          [question],
        ),
        returnValue:
            _i5.Future<_i2.InterviewQuestion>.value(_FakeInterviewQuestion_0(
          this,
          Invocation.method(
            #updateQuestion,
            [question],
          ),
        )),
      ) as _i5.Future<_i2.InterviewQuestion>);

  @override
  _i5.Future<void> deleteQuestion(String? questionId) => (super.noSuchMethod(
        Invocation.method(
          #deleteQuestion,
          [questionId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i3.QuestionCategoryEntity>> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i5.Future<List<_i3.QuestionCategoryEntity>>.value(
            <_i3.QuestionCategoryEntity>[]),
      ) as _i5.Future<List<_i3.QuestionCategoryEntity>>);

  @override
  _i5.Future<_i3.QuestionCategoryEntity> createCategory(
          _i3.QuestionCategoryEntity? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCategory,
          [category],
        ),
        returnValue: _i5.Future<_i3.QuestionCategoryEntity>.value(
            _FakeQuestionCategoryEntity_1(
          this,
          Invocation.method(
            #createCategory,
            [category],
          ),
        )),
      ) as _i5.Future<_i3.QuestionCategoryEntity>);

  @override
  _i5.Future<List<_i2.InterviewQuestion>> bulkCreateQuestions(
          List<Map<String, dynamic>>? questionsData) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkCreateQuestions,
          [questionsData],
        ),
        returnValue: _i5.Future<List<_i2.InterviewQuestion>>.value(
            <_i2.InterviewQuestion>[]),
      ) as _i5.Future<List<_i2.InterviewQuestion>>);

  @override
  _i5.Future<List<_i3.QuestionCategoryEntity>> bulkCreateCategories(
          List<Map<String, dynamic>>? categoriesData) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkCreateCategories,
          [categoriesData],
        ),
        returnValue: _i5.Future<List<_i3.QuestionCategoryEntity>>.value(
            <_i3.QuestionCategoryEntity>[]),
      ) as _i5.Future<List<_i3.QuestionCategoryEntity>>);

  @override
  _i5.Future<Map<String, dynamic>> getQuestionStats() => (super.noSuchMethod(
        Invocation.method(
          #getQuestionStats,
          [],
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> initializeDefaultQuestions() => (super.noSuchMethod(
        Invocation.method(
          #initializeDefaultQuestions,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
